receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
        read_buffer_size: 512 KiB
        write_buffer_size: 512 KiB
        keepalive:
          server_parameters:
            max_connection_idle: 15s
            max_connection_age: 30s
            max_connection_age_grace: 5s
            time: 5s
            timeout: 20s
      http:
        endpoint: 0.0.0.0:4318

exporters:
  debug:
    verbosity: detailed

  prometheus:
    endpoint: "0.0.0.0:8889"
    const_labels:
      label1: value1

  logging:

  zipkin:
    endpoint: "http://valiant-enjoyment.railway.internal:9411/api/v2/spans"
    format: proto

  otlp/jaeger:
    endpoint: overflowing-acceptance.railway.internal:4317
    tls:
      insecure: true

processors:
  batch:

extensions:
  health_check:
  pprof:
    endpoint: :1888
  zpages:
    endpoint: :55679

service:
  extensions: [pprof, zpages, health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, zipkin, otlp/jaeger, debug]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, prometheus, debug]
